xresfree: improve killing

diff --git a/bin/xresfree b/bin/xresfree
--- a/bin/xresfree
+++ b/bin/xresfree
@@ -4,20 +4,30 @@ bases=$(xrestop -b -m 1 \
     | grep '<unknown>' -A 1 \
     | awk '/res_base/ { print $3; }' \
     | sed 's/^ox/0x/' \
-    | grep -oE '.{5}')
+    | grep -oE '.{8}')
 
+amount=$(wc -l <<< "${bases}")
+echo ":: found ${amount} resource bases with <unknown> identifier" >&2
 
-regexp_bases=$(printf "%s|" $bases)
-regexp_bases="(${regexp_bases%|})"
+root=$(xwininfo -root -all)
+for base in ${bases[@]}; do
+    windows=$(awk "/^\s+$base/ { print \$1; }" <<< "$root")
+    if [[ ! "$windows" ]]; then
+        echo ":: [$base] there is no window with such res_base" >&2
+        continue
+    fi
 
-xwininfo -root -all \
-    | awk "/^\s+$regexp_bases/ { print \$1; }" \
-    | while read windowid; do
-        logger "xkill -id $windowid"
+    amount=$(wc -l <<< "$windows")
+    echo ":: [$base] found ${#amount} windows" >&2
 
-        if xkill -id "$windowid"; then
-            echo "[success] $windowid"
+    if [[ ${#amount} -eq 1 ]]; then
+        if xkill -id "$windows"; then
+            echo ":: [$base] $windows: killed"
         else
-            echo "[failure] $windowid"
+            echo ":: [$base] $windows: error"
         fi
-    done
+    else
+        echo ":: [$base] too much windows, skipping" >&2
+        continue
+    fi
+done
